---
version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"

  data-warehouse:
    container_name: data-warehouse
    image: ahmadnawawi99/data-warehouse:0.1
    pull_policy: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/clustered_data_warehouse
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    restart: on-failure